### ISSUE TITLE
List Messages is broken when a message has an object recipient

### ISSUE THREAD

**Issue by troylelandshields** [knocklabs/knock-go#36]
The docs say that a message's recipient will either be the ID as a string OR if it is an Object then it will be an object with the collection and ID.

![image](https://github.com/user-attachments/assets/be54df1b-5cd3-4592-889b-e0a2c2414850)

The `Message` struct only supports string.
![image](https://github.com/user-attachments/assets/570fb78f-e601-40f5-9e3f-05a032f1dc41)

Which means when you try to get a message from the API that has an object as its recipient, you end up getting this error:

```
"json: cannot unmarshal object into Go struct field Message.items.recipient of type string
```

**Comment by troylelandshields** [comment]
I see, there's a separate interface called ObjectsService. I think you'd run into this problem if you have a mix of Object recipients and non-object recipients... but I could be wrong. Either way it _seems_ like the ObjectsService is working for what I need so I'll go ahead and close this, thanks!

**Comment by brentjanderson** [comment]
Glad you found a workaround @troylelandshields - do drop a note if you find that it's not working after all, or drop into our [Customer slack](https://knock.app/join-slack) if you haven't yet!

**Comment by troylelandshields** [comment]
My workaround didn't work, but looks like the real fix is to just make sure I'm using the latest version since you guys ahve already fixed this :)
